name = "example_project"
version = "0.1.0"
license = "BSD3"
author = "Author"
maintainer = "example@example.com"
copyright = "2020 Author"
dependencies = []
compiler = "gfortran"

[[executable]]
name = "example_project"
source-dir = "app"
main = "main.f90"
dependencies = []
