name = "example_project"
version = "0.1.0"
license = "BSD3"
author = "Author"
maintainer = "example@example.com"
copyright = "2020 Author"
dependencies = []
compiler = "gfortran"
devel-options = ["-g", "-Wall", "-Wextra", "-Werror", "-pedantic"]
release-options = ["-O3"]

[library]
source-dirs = "src"

[executables.Hello_world]
main = "Hello_world.f90"
source-dirs = "app"
linker-options = ["-O3"]
dependencies = []
