name = "example_project"
version = "0.1.0"
license = "BSD3"
author = "Author"
maintainer = "example@example.com"
copyright = "2020 Author"
dependencies = []
compiler = "gfortran"

[executables.example_project]
main = "main.f90"
source-dir = "app"
dependencies = []
