name = "package-name"
version = "0.1.0"
license = "BSD3"
author = "Author name here"
maintainer = "example@example.com"
copyright = "2020 Author name here"
dependencies = ["../std-lib.tar.gz"]
compiler = "gfortran"
devel-options = ["-g", "-Wall", "-Wextra", "-Werror", "-pedantic"]
release-options = ["-O3"]

[library]
source-dirs = "src"

[executables.executable-name]
main = "Main.f90"
source-dirs = "app"
linker-options = ["-O3"]
dependencies = ["iso_varying_string"]

[tests.test-name]
main = "Spec.f90"
source-dirs = "test"
linker-options = ["-Og"]
dependencies = ["vegetables >= 1.0 && < 2.0"]
