name = "fpm"
version = "0.1.0"
license = "MIT"
author = "fpm maintainers"
maintainer = ""
copyright = "2020 fpm contributors"

[dependencies]
toml-f = { git = "https://github.com/toml-f/toml-f" }

[[test]]
name = "fpm-test"
source-dir = "test"
main = "main.f90"
